services:
  mongo:
    image: mongo:8
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  server:
    image: node:22
    working_dir: /usr/src/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ./wsei-communicator-server:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm run dev"
    ports:
      - "3000:3000"
    env_file:
      - ./wsei-communicator-server/.env
    depends_on:
      - mongo

  client:
    image: node:22
    working_dir: /usr/src/app
    volumes:
      - ./wsei-communicator-client:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm run dev -- --host --port 5173"
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  mongo-data:
